Set up tests
SW7-Decentralized-voting/blockchain pull request #8
Opened 2024-11-01 13:35 UTC by Fantaskink

- Added route test
- Added utils tests
- Refactored microservice

2024-11-01 13:41 UTC, TheMOHD3886 submitted a review, later dismissed
lgtm bruva 👍

2024-11-01 13:54 UTC, MortenMunk requested changes
Just some consideration for testing, and some linting reminders

2024-11-01 13:54 UTC, MortenMunk commented on test/utils/convertBigIntToString.test.js
We should probably test edge cases where ytou try to convert a char or string to bigint, so we know if behaves how we want (e.g throws an error)

2024-11-01 13:54 UTC, MortenMunk commented on utils/startContract.js
Remember to have linter ignore console logs, if they are meant to be in the code

2024-11-01 13:55 UTC, Mafusn requested changes
LGTM, maybe too few test cases

2024-11-01 13:55 UTC, Mafusn commented on test/utils/stopContract.test.js
Put into one Describe() only

2024-11-01 13:55 UTC, Mafusn commented on test/utils/startContract.test.js
Put into one Describe() only

2024-11-01 13:55 UTC, Mafusn commented on test/routes/partyRoutes.test.js
Put into one Describe() only i think, not so sure about this one

2024-11-01 13:55 UTC, Mafusn commented on test/routes/candidateRoutes.test.js
Put into one Describe() only

2024-11-01 14:00 UTC, Mafusn submitted a review, later dismissed
Lets goooo

2024-11-01 14:03 UTC, MortenMunk approved these changes, later dismissed
LGTM once linting is fixed

2024-11-04 10:05 UTC, TheMOHD3886 approved these changes
lgtm dawg 👍

2024-11-04 10:10 UTC, Mafusn approved these changes

2024-11-04 10:11 UTC, merged